name: Dev Build

on:
  workflow_dispatch:
    inputs:
      push:
        description: "Push to Docker Hub"
        type: boolean
        required: true
        default: true

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: inputs.push == true
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build (and optionally push) dev images
        uses: docker/bake-action@v5
        with:
          push: ${{ inputs.push }}
          files: ./docker-bake.hcl
          targets: |
            devpush
            devpush5090

